/*
 * File: app/store/StyleStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MusicApp.store.StyleStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MusicApp.model.AblumList'
    ],

    config: {
        data: [
            {
                title: '新歌榜',
                id: 1
            },
            {
                title: '热歌榜',
                id: 2
            },
            {
                title: '摇滚榜',
                id: 11
            },
            {
                title: '爵士榜',
                id: 12
            },
            {
                title: '流行榜',
                id: 16
            },
            {
                title: '欧美金曲榜',
                id: 21
            },
            {
                title: '经典老歌榜',
                id: 22
            },
            {
                title: '情歌对唱榜',
                id: 23
            },
            {
                title: '影视金曲榜',
                id: 24
            },
            {
                title: '网络歌曲榜',
                id: 25
            }
        ],
        model: 'MusicApp.model.AblumList',
        storeId: 'StyleStore'
    }
});