/*
 * File: app/view/AreaList.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MusicApp.view.AreaList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.areaList',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        height: '100%',
        itemId: 'styleList1',
        store: 'AreaStore',
        itemTpl: [
            '<div>{title}</div>'
        ]
    }

});