/*
 * File: app/view/MusicPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MusicApp.view.MusicPanel', {
    extend: 'Ext.Container',
    alias: 'widget.musicPanel',

    config: {
        fullscreen: false,
        height: 100,
        hidden: false,
        html: '<div class="mp"> 	<div class="mp-box"> 		 		<img src="img/mplayer_error.png" alt="music cover" class="mp-cover"> 		 		<div class="mp-info"> 			<p class="mp-name">暂无歌曲</p> 			<p class="mp-singer">歌手名</p> 			<p><span class="mp-time-current">00:00</span>/<span class="mp-time-all">00:00</span></p> 		</div> 		<div class="mp-btn"> 			<button class="mp-prev" title="上一首"></button> 			<button class="mp-pause" title="播放"></button> 			<button class="mp-next" title="下一首"></button> 			<button class="mp-mode" title="播放模式"></button> 		</div> 		<div class="mp-pro"> 			<div class="mp-pro-current"></div> 		</div> 	</div> 	<button class="mp-toggle"> 		<span class="mp-toggle-img"></span> 	</button> 	<div class="mp-lrc-box mp-lrc-show"> 		<ul class="mp-lrc"></ul> 	</div> 	<div class="mp-list-box"> 		<ul class="mp-list-title"></ul> 		<table class="mp-list-table"> 			<thead> 				<tr> 					<th>歌名</th> 					<th>歌手</th> 					<th>时长</th> 				</tr> 			</thead> 			<tbody class="mp-list"></tbody> 		</table> 	</div> </div>',
        top: '85%',
        width: '100%'
    }

});